### ISSUE TITLE
Review doc for new changes

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-guides/gmail-spreadsheet-integration#24]
**Description:**
Review PR #23 for doc changes.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Closing as we no longer maintain this repo.
